version: "3.4"

services:
  db:
    image: postgis/postgis:13-3.0
    env_file:
      - ./docker/env.db
    volumes:
      - db_data:/var/lib/postgresql/data/

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: "./manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./docker/env.db
      - ./.env
    container_name: django_learn
    ports:
      - "8000:8000"
      
    volumes:
      - .:/opt/code
    depends_on:
      - db

volumes:
  db_data:
