name: Build Integration

on:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: System Update
        run: sudo apt-get update
      - name: Install gdal
        run: sudo apt-get install -y gdal-bin
      - name: Setup Python 3.9
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Run Tests
        run: |
          ./manage.py test

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: pip
      - uses: pre-commit/action@v2.0.3
